version: 0.0
os: linux
files:
  - source:  /
    destination:  /home/ec2-user/deploy

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    mode: 755

hooks:
  AfterInstall:
    - location: start.sh
      timeout: 60
      runas: root
